name: 🐛 Problème NOVA
description: Signaler un problème simplement
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Qu'est-ce qui ne marche pas ?
      placeholder: Explique simplement ce que tu vois...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Qu'est-ce que tu voulais obtenir ?
      placeholder: Ce que NOVA aurait dû faire...
